"""Central configuration for the RAG document Q&A system."""
import os
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data"
INDEX_DIR = ROOT_DIR / "index"
DATA_DIR.mkdir(exist_ok=True)
INDEX_DIR.mkdir(exist_ok=True)

# Embeddings (local, no API key required)
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

# Chunking
CHUNK_SIZE = 500          # characters
CHUNK_OVERLAP = 80

# Retrieval
TOP_K = 4                 # final chunks passed to the LLM
CANDIDATE_K = 12          # candidates before reranking
BM25_WEIGHT = 0.4         # hybrid: weight on lexical vs. dense score
DENSE_WEIGHT = 0.6

# LLM (optional). If OPENAI_API_KEY is set, answers are generated by the LLM;
# otherwise the system falls back to an extractive answer from the top chunks.
LLM_MODEL = "gpt-4o-mini"
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
USE_LLM = bool(OPENAI_API_KEY)
